In [1]:
import sys
print(sys.version)

3.7.2 (default, Feb 17 2020, 01:13:00) 
[GCC 5.4.0 20160609]


In [2]:
import sys
print(sys.version)
import numpy as np

3.7.2 (default, Feb 17 2020, 01:13:00) 
[GCC 5.4.0 20160609]


In [17]:
x = np.array([3, 1, 2])

In [18]:
np.argsort(x)

array([1, 2, 0])

In [19]:
x.argmax()  

0

In [9]:
x = np.array([[0, 3], [2, 2]])

In [10]:
x

array([[0, 3],
       [2, 2]])

In [11]:
np.argsort(x, axis=0)  # sorts along first axis (down)

array([[0, 1],
       [1, 0]])

In [12]:
np.argsort(x, axis=1)  # sorts along last axis (across)

array([[0, 1],
       [0, 1]])

In [48]:
np.bincount(np.arange(5))

np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))# yineleme sayısını verir

array([1, 3, 1, 1, 0, 0, 0, 1])

In [49]:
y_train = [14,1,1,3,6,9,7,8,1,2]
dists = np.array([14,1,1,3,6,9,7,8,1,2])

In [54]:
print(dists)
dists_folds = []
dists_folds = np.array_split(dists, 5)
print(dists_folds)

[14  1  1  3  6  9  7  8  1  2]
[array([14,  1]), array([1, 3]), array([6, 9]), array([7, 8]), array([1, 2])]


In [47]:
dists_folds
num_test = dists.shape[0]

In [37]:
num_test

10

In [41]:
for i in range(num_test):
    closest_y = []
    closest_y = np.argsort(dists[i])